name: main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install .
    - name: Lint with pylint
      run: |
        pip install pylint
        # stop the build if there are Python syntax errors or undefined names
        pylint solcast tests --rcfile=.pylintrc
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest -v --cov=solcast --cov-report=term-missing -l --junitxml=pytest-report.xml --cov-report=xml:coverage.xml tests/
